import type { FlowConfig, SpanMapping } from '../core/types'

export const spanMapping: SpanMapping = {
  'rrq:queue:mail-backfill': 'batchfill-queue',
  'rrq:queue:mail-incoming': 'incoming-queue',
  'rrq:queue:mail-analyze': 'analyze-queue',
  'rrq:queue:mail-extract': 'extract-queue',
  'rrq:queue:mail-send': 'send-queue',

  handle_mail_backfill_start: 'batchfill-worker',
  handle_mail_backfill_chunk: 'batchfill-worker',
  handle_mail_incoming_check: 'incoming-worker',
  handle_mail_analyze_reply: 'analyze-worker',
  handle_mail_extract: 'extract-worker',
  handle_mail_send_reply: 'send-worker',
  handle_mail_cron_tick: 'cron-scheduler',

  mail_batchfill: 'batchfill-worker',
  mail_incoming: 'incoming-worker',
  mail_analyze: 'analyze-worker',
  mail_extract: 'extract-worker',
  mail_send: 'send-worker',

  threads_written: 'write-threads',
  metadata_written: 'postgres-main',
  cursor_updated: 'check-process',
}

const boundaryLayout = {
  fullstack: {
    position: { x: -40, y: 10 },
    size: { width: 1780, height: 1700 },
    minSize: { width: 1200, height: 900 },
  },
  resqAgent: {
    position: { x: 170, y: 70 },
    size: { width: 1460, height: 1560 },
    minSize: { width: 900, height: 700 },
  },
} as const

const showBoundaryFrames = false

const boundaryFrameNodes: FlowConfig['nodes'] = [
  {
    id: 'fullstack-group',
    type: 'group',
    label: 'FULLSTACK',
    style: { color: 'gray', borderStyle: 'dashed' },
    position: boundaryLayout.fullstack.position,
    size: boundaryLayout.fullstack.size,
    minSize: boundaryLayout.fullstack.minSize,
    resizable: true,
    draggable: false,
    selectable: true,
  },
  {
    id: 'resq-agent-group',
    type: 'group',
    label: 'RESQ-AGENT',
    style: { color: 'gray', borderStyle: 'dashed' },
    position: boundaryLayout.resqAgent.position,
    size: boundaryLayout.resqAgent.size,
    minSize: boundaryLayout.resqAgent.minSize,
    resizable: true,
    draggable: false,
    selectable: true,
  },
]

export const mailPipelineFlow: FlowConfig = {
  id: 'mail-pipeline',
  name: 'Mail Pipeline',
  description: 'Real-time view of enqueue, worker, and persistence steps for mail processing.',
  nodes: [
    ...(showBoundaryFrames ? boundaryFrameNodes : []),

    { id: 'trigger-oauth', type: 'pill', label: 'Vendor email account connected', style: { color: 'green' }, position: { x: 20, y: 100 } },
    {
      id: 'batchfill-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-batchfill',
      style: { color: 'yellow', icon: 'queue' },
      position: { x: 260, y: 90 },
    },
    {
      id: 'batchfill-worker',
      type: 'rectangle',
      label: 'mail_batchfill',
      style: { color: 'blue', icon: 'worker' },
      position: { x: 260, y: 220 },
    },
    {
      id: 'cron-scheduler',
      type: 'roundedRect',
      label: 'rpq cron - handle_mail_cron_tick (1min)',
      style: { color: 'gray', icon: 'cron' },
      position: { x: 80, y: 340 },
      size: { width: 220, height: 88 },
    },
    {
      id: 'incoming-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-incoming',
      style: { color: 'yellow', icon: 'queue' },
      position: { x: 260, y: 460 },
    },
    {
      id: 'incoming-worker',
      type: 'rectangle',
      label: 'mail_incoming',
      style: { color: 'blue', icon: 'worker' },
      position: { x: 260, y: 580 },
    },
    {
      id: 'check-process',
      type: 'roundedRect',
      label: 'handle_checking_check',
      style: { color: 'gray' },
      position: { x: 70, y: 710 },
    },
    { id: 's3', type: 'circle', label: 'S3', style: { color: 'blue', icon: 's3' }, position: { x: 710, y: 530 } },
    {
      id: 'postgres-main',
      type: 'circle',
      label: 'Postgres',
      style: { color: 'blue', icon: 'postgres' },
      position: { x: 500, y: 740 },
    },
    {
      id: 'write-threads',
      type: 'roundedRect',
      label: 'write new mail threads to S3',
      style: { color: 'blue' },
      position: { x: 500, y: 600 },
    },
    {
      id: 'extract-enqueue',
      type: 'badge',
      label: 'enqueue handle_mail_extract',
      style: { color: 'gray' },
      position: { x: 470, y: 760 },
    },
    {
      id: 'analyze-enqueue',
      type: 'badge',
      label: 'enqueue handle_mail_analyze_reply',
      style: { color: 'gray' },
      position: { x: 470, y: 830 },
    },
    {
      id: 'analyze-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-analyze',
      style: { color: 'yellow', icon: 'queue' },
      position: { x: 780, y: 740 },
    },
    {
      id: 'analyze-worker',
      type: 'rectangle',
      label: 'mail_analyze',
      style: { color: 'blue', icon: 'worker' },
      position: { x: 780, y: 860 },
    },
    {
      id: 'analyze-decision',
      type: 'diamond',
      label: 'action?',
      style: { color: 'orange' },
      position: { x: 780, y: 980 },
    },
    { id: 'skip-node', type: 'rectangle', label: 'skip', style: { color: 'gray' }, position: { x: 1080, y: 940 } },
    {
      id: 'draft-reply',
      type: 'rectangle',
      label: 'Insert reply draft into mail_reply_drafts',
      style: { color: 'orange' },
      position: { x: 680, y: 1110 },
      size: { width: 240, height: 95 },
    },
    {
      id: 'autosend-decision',
      type: 'diamond',
      label: 'Autosend?',
      style: { color: 'orange' },
      position: { x: 680, y: 1250 },
    },
    {
      id: 'stop-review',
      type: 'octagon',
      label: 'STOP - await human review',
      style: { color: 'red' },
      position: { x: 1000, y: 1230 },
      size: { width: 210, height: 130 },
    },
    {
      id: 'set-sending',
      type: 'rectangle',
      label: "set status = 'sending', enqueue SendReply",
      style: { color: 'blue' },
      position: { x: 680, y: 1400 },
      size: { width: 230, height: 90 },
    },

    {
      id: 'extract-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-extract',
      style: { color: 'yellow', icon: 'queue' },
      position: { x: 1180, y: 740 },
    },
    {
      id: 'extract-worker',
      type: 'rectangle',
      label: 'mail_extract',
      style: { color: 'blue', icon: 'worker' },
      position: { x: 1180, y: 860 },
    },
    { id: 'run-extract', type: 'rectangle', label: 'run_extract()', style: { color: 'blue' }, position: { x: 1180, y: 980 } },
    {
      id: 'extract-success',
      type: 'diamond',
      label: 'success?',
      style: { color: 'orange' },
      position: { x: 1180, y: 1110 },
    },
    {
      id: 'record-extract-state',
      type: 'rectangle',
      label: 'record_extract_state',
      style: { color: 'gray' },
      position: { x: 1180, y: 1250 },
    },
    {
      id: 'upsert-contacts',
      type: 'badge',
      label: 'upsert_contact(s) to mail_extracted...',
      style: { color: 'blue' },
      position: { x: 1440, y: 1100 },
    },
    {
      id: 'postgres-extract',
      type: 'circle',
      label: 'Postgres',
      style: { color: 'blue', icon: 'postgres' },
      position: { x: 1440, y: 1250 },
    },

    {
      id: 'send-queue',
      type: 'roundedRect',
      label: 'rrq:queue:mail-send',
      style: { color: 'yellow', icon: 'queue' },
      position: { x: 680, y: 1550 },
    },
    {
      id: 'send-worker',
      type: 'rectangle',
      label: 'mail_send',
      style: { color: 'blue', icon: 'worker' },
      position: { x: 680, y: 1670 },
    },
    {
      id: 'send-process',
      type: 'rectangle',
      label: 'handle_mail_send_reply',
      style: { color: 'blue' },
      position: { x: 680, y: 1790 },
    },
    {
      id: 'send-outcome',
      type: 'diamond',
      label: 'sent/send_failed/stale?',
      style: { color: 'orange' },
      position: { x: 680, y: 1920 },
    },
    { id: 'retry-node', type: 'badge', label: 'retry', style: { color: 'orange' }, position: { x: 980, y: 1920 } },
    {
      id: 'terms-annotation',
      type: 'annotation',
      label: 'TERMS:\nmail thread = gmail conversation\nmail message = individual email\nreply draft = staged response prior to send',
      position: { x: 930, y: 260 },
      size: { width: 280, height: 130 },
    },
  ],

  edges: [
    { id: 'e-trigger-batchfill', source: 'trigger-oauth', target: 'batchfill-queue', type: 'dashed' },
    { id: 'e-batchfill-q-worker', source: 'batchfill-queue', target: 'batchfill-worker' },
    { id: 'e-cron-incoming-q', source: 'cron-scheduler', target: 'incoming-queue', label: 'enqueue' },
    { id: 'e-incoming-q-worker', source: 'incoming-queue', target: 'incoming-worker' },
    { id: 'e-incoming-worker-check', source: 'incoming-worker', target: 'check-process' },
    { id: 'e-incoming-worker-write', source: 'incoming-worker', target: 'write-threads' },
    { id: 'e-write-s3', source: 'write-threads', target: 's3' },
    { id: 'e-write-pg', source: 'write-threads', target: 'postgres-main', label: 'write metadata' },
    { id: 'e-check-pg', source: 'check-process', target: 'postgres-main' },
    { id: 'e-incoming-extract-enqueue', source: 'incoming-worker', target: 'extract-enqueue' },
    { id: 'e-incoming-analyze-enqueue', source: 'incoming-worker', target: 'analyze-enqueue' },
    { id: 'e-extract-enqueue-q', source: 'extract-enqueue', target: 'extract-queue' },
    { id: 'e-analyze-enqueue-q', source: 'analyze-enqueue', target: 'analyze-queue' },
    { id: 'e-analyze-q-worker', source: 'analyze-queue', target: 'analyze-worker' },
    {
      id: 'e-analyze-worker-decision',
      source: 'analyze-worker',
      target: 'analyze-decision',
      targetHandle: 'analyze-decision-in-top',
    },
    {
      id: 'e-analyze-skip',
      source: 'analyze-decision',
      sourceHandle: 'analyze-decision-out-right',
      target: 'skip-node',
      label: 'action = skip',
      type: 'dashed',
    },
    {
      id: 'e-analyze-draft',
      source: 'analyze-decision',
      sourceHandle: 'analyze-decision-out-bottom',
      target: 'draft-reply',
      label: 'action = draft_reply',
    },
    {
      id: 'e-draft-autosend',
      source: 'draft-reply',
      target: 'autosend-decision',
      targetHandle: 'autosend-decision-in-top',
    },
    {
      id: 'e-autosend-stop',
      source: 'autosend-decision',
      sourceHandle: 'autosend-decision-out-right',
      target: 'stop-review',
      label: 'no -> elo = 0',
      type: 'dashed',
    },
    {
      id: 'e-autosend-send',
      source: 'autosend-decision',
      sourceHandle: 'autosend-decision-out-bottom',
      target: 'set-sending',
      label: 'yes',
    },
    { id: 'e-set-sending-queue', source: 'set-sending', target: 'send-queue' },

    { id: 'e-extract-q-worker', source: 'extract-queue', target: 'extract-worker' },
    { id: 'e-extract-worker-run', source: 'extract-worker', target: 'run-extract' },
    {
      id: 'e-run-extract-success',
      source: 'run-extract',
      target: 'extract-success',
      targetHandle: 'extract-success-in-top',
    },
    {
      id: 'e-extract-success-record',
      source: 'extract-success',
      sourceHandle: 'extract-success-out-bottom',
      target: 'record-extract-state',
      label: 'success',
    },
    {
      id: 'e-extract-success-upsert',
      source: 'extract-success',
      sourceHandle: 'extract-success-out-right',
      target: 'upsert-contacts',
      label: 'success + contacts',
    },
    { id: 'e-upsert-pg', source: 'upsert-contacts', target: 'postgres-extract' },
    { id: 'e-record-pg', source: 'record-extract-state', target: 'postgres-extract' },

    { id: 'e-send-q-worker', source: 'send-queue', target: 'send-worker' },
    { id: 'e-send-worker-process', source: 'send-worker', target: 'send-process' },
    {
      id: 'e-send-process-outcome',
      source: 'send-process',
      target: 'send-outcome',
      targetHandle: 'send-outcome-in-top',
    },
    {
      id: 'e-send-outcome-retry',
      source: 'send-outcome',
      sourceHandle: 'send-outcome-out-right',
      target: 'retry-node',
      label: 'retry',
      type: 'dashed',
    },
    {
      id: 'e-stop-review-send-q',
      source: 'stop-review',
      target: 'send-queue',
      label: 'status = needs_review',
      type: 'dashed',
    },
  ],

  spanMapping,
}
